image: docker:latest
services:
    - docker:dind

stages: 
  - build
  - deploy

build:
  stage: build
  only:
    - master
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest

deploy:
  stage: deploy
  only:
    - master
  before_script:
    - apk add --no-cache openssh openssh-client bash rsync
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - bash -c 'ssh-add <(echo "$DEPLOY_PRIVATE_KEY")'
  script:
    - rsync -avz --port=2231 --delete ./ root@$SERVER_ADDR:/usr/app/source/
    - ssh -p2231 root@$SERVER_ADDR "/usr/app/source/deploy.bash -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD -r $CI_REGISTRY -i $CI_REGISTRY_IMAGE"